version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /tmp:/tmp
  app:
    image: php:7.3-fpm
    volumes:
      - ./www:/var/www
      - ./php-fpm/:/usr/local/etc/php-fpm.d/
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /tmp:/tmp
